### ISSUE TITLE
docker run reports '0.0.0', docker image likely stale

### ISSUE THREAD

**Issue by xkortex** [mdomke/git-semver#13]
Neat tool! But the docker run command in your readme seems to be broken. `2bb1e6967c61` is the image hash. 

`$ docker run --rm -v ${PWD}:/git-semver  mdomke/git-semver`

`0.0.0` 

Expected: 
`$ docker run --rm -v ${PWD}:/git-semver -w /git-semver alpine/git describe`

`v0.0.2-9-g64dbbb8`

BUT, if I force the workdir, it seems to work fine: 

`$ docker run --rm -v ${PWD}:/git-semver -w /git-semver mdomke/git-semver` 

`0.0.5-dev1+g64dbbb8`

`$ docker inspect mdomke/git-semver | grep -i work` 

`            "WorkingDir": "",`

But if I rebuild the image from latest master, `            "WorkingDir": "/git-semver",`. So I think your dockerhub image is just stale.

**Comment by mdomke** [comment]
Sorry that it took me almost 4 months to take care of this issue. The image has been rebuilt on the docker hub and should now behave as expected. At least I get
```
λ docker run --rm -v ${PWD}:/git-semver mdomke/git-semver
v6.0.2
```
when using the implicit `latest` tag in the git-semver repository. 

I will nevertheless migrate the image building to GitHub actions as soon as I find the time. Thank you for the heads-up!

**Comment by xkortex** [comment]
You're welcome! I've been using it to great effect such that coworkers don't have to install it directly. I have a makefile stanza like
```
GIT_SEMVER = git-semver || docker run --rm -v `pwd`:/git-semver mdomke/git-semver
# Print the version, based on the git semver
version:
	@$(GIT_SEMVER)
```
so as long as they have docker already running, they can just fire `make` right out of the box. Such a time saver!
