### ISSUE TITLE
Strip leading characters in git tag

### ISSUE THREAD

**Issue by sjdrc** [mdomke/git-semver#22]
Hi there, thanks for making this tool.

We create our git tags with a leading `v` i.e. v1.2.3.

I am creating automatic helm releases in CI and `git-semver` includes the leading v as our tags include this.

The leading `v` is actually [not SemVer compliant](https://semver.org/#is-v123-a-semantic-version). Would it be possible for you to add an option to strip any leading characters?

**Comment by mdomke** [comment]
I added a `-no-prefix`-option in release `6.7.1`.
