### ISSUE TITLE
Add --match option to match a tag pattern (like git describe --match <pattern>)

### ISSUE THREAD

**Issue by ringlej** [mdomke/git-semver#26]
It would be very useful to have an option to only consider tags that match a pattern. Like `git describe --match <pattern>` does.
This would allow a usecase where you might have a file `VERSION-TAG` in your repo and you call git-semver as:
`git-semver --no-prefix --match $(cat VERSION-TAG)`
This would allow better branch management of your repo.
Here is a simplified scenario:

```
          D---E---F
         /
A---B---C---G---H---I
```
* A is tagged `v0.1.0-alpha` and has `VERSION-TAG` as `v0.1.0-alpha`
* B's version is `0.1.0-alpha.dev.1+meta`
* C is tagged with both `v1.0.0-rc` and `v1.1.0-alpha`. C's commit also changes `VERSION-TAG` to `v1.0.0` (this will match the `v1.0.0-rc` tag).
* D's commit changes `VERSION-TAG` to `v1.1.0-alpha`. D's version is `1.1.0-alpha.dev.1+meta`. F's version is `1.1.0-alpha.dev.3+meta`
* G's versoin is `1.0.0-rc.dev.1+meta`. H's version is `1.0.0-rc.dev.2+meta`
* I is tagged as `v1.0.0` and I's version is `1.0.0`

**Comment by mdomke** [comment]
This sound like a legit idea. Would you feel comfortable to provide a PR?

**Comment by mdomke** [comment]
This is now implemented in version `v6.8.1`. Let me know if this suits your needs.
