### ISSUE TITLE
dev prefix prevents proper sorting

### ISSUE THREAD

**Issue by choffmeister** [mdomke/git-semver#8]
An example of a version generated by this tool is `3.5.2-dev22+gbaf822dd5`. This has a problem as https://semver.org/#spec-item-9 defines, that non numeric prerelease identifiers are to be sorted as text. That is

`3.5.2-dev22+gbaf822dd5` < `3.5.2-dev3+gbaf822dd5` (`dev22` must be compared with `dev3`)

To fix this the `dev` prefix and the number should be split by a dot, so that the correct order

`3.5.2-dev.3+gbaf822dd5` < `3.5.2-dev.22+gbaf822dd5` (the parts `3` and `22` are pure numeric, hence compared as number and not as strings)

would apply.

**Comment by choffmeister** [comment]
There is more wrong with how you generate the versions:

According to the readme the commit `4.2.0-rc3-5-fcf2c8f` becomes `4.2.0-rc4.dev5-fcf2c8f`. But semver says, that for two prereleases the version with more segments is higher should the rest be equal. That means

`4.2.0-rc3` < `4.2.0-rc4` < `4.2.0-rc4.dev5-fcf2c8f`

The correct way to generate the version would be tu just append the dev.5 stuff:

`4.2.0-rc3` < `4.2.0-rc3.dev5-fcf2c8f` < `4.2.0-rc4`

**Comment by mdomke** [comment]
This was [fixed in version](https://github.com/mdomke/git-semver/blob/master/CHANGELOG.md#500---2020-10-08) `v5.0.0`
